name: MERN Stack CI/CD Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Copy code and run with ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/mern-app
            cd ~/mern-app

            sudo docker-compose down --remove-orphans || true

      - name: Copy files on VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/azureuser/mern-app"

      - name: Run Docker Compose on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            cd ~/mern-app
            sudo docker-compose up --build -d
